# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Create migrations
      run: |
        python migrate.py db init
        python migrate.py db migrate
        python migrate.py db upgrade
    - name: Test with unittest
      run: |
        python -m unittest test.RepositoryTest
    - name: Coverage
      run: |
        coverage run  -m unittest test.RepositoryTest
        coverage xml
    - name: SonarCloud Scan
      env:
        SONAR_TOKEN: 08046fc593cf7114b8447e29efcfa68187429bb1
        GITHUB_TOKEN: 532968b46693896f00147d7a350fbf020dea58b0
      uses: SonarSource/sonarcloud-github-action@v1.1

